#include "General.h"

#define TOPICO_UMIDADE_1 "board/umidade/1"
#define TOPICO_TEMPERATURA_1 "board/temperatura/1"
#define TOPICO_UMIDADE_2 "board/umidade/2"
#define TOPICO_TEMPERATURA_2 "board/temperatura/2"
#define TOPICO_UMIDADE_3 "board/umidade/3"
#define TOPICO_TEMPERATURA_3 "board/temperatura/3"
#define TOPICO_DHT11_1 "board/dht11/1"
#define TOPICO_DHT11_2 "board/dht11/2"
#define TOPICO_DHT11_3 "board/dht11/3"
